version: '3.8'

services:
  app:
    build: 
      context: .
    # este servicio se puede usar sin nginx pero debes habilitar los puertos
    # ports:
    #   - "90:90"
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 90
    expose:
      - 90
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    volumes:
      - ./app:/app/

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=redis.diego-luque.com
      - LETSENCRYPT_HOST=redis.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

networks:
  default:
    name: web_private_red_webapps
    external: true
