# Usa la imagen de Nginx como base
FROM nginx

# Copia el archivo de configuración personalizado de Nginx al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para Nginx
EXPOSE 80

# Comando para iniciar Nginx en primer plano al ejecutar el contenedor
CMD ["nginx", "-g", "daemon off;"]